platform :ios, '11.0'
use_frameworks!

target 'ThreeLevelAccordian_Example' do

  pod 'FunAccordionView', :path => '..'

  target 'ThreeLevelAccordian_Tests' do

    inherit! :search_paths

  end
end
